version: "3.9"
services:
  web:
    image: avo-server-docker
    build: .
    command: "npm start"
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: "mongo"
    ports:
    - "27017:27017"